export default {
  namespaced: true,
  state: {
      beneficios: "Si estás leyendo esto ahora, es porque tienes parte de nuestro espíritu en ti. Todo este tiempo ha sido una gran montaña rusa, llena de experiencias que nunca antes habíamos vivido como personas y como industria. Partiendo desde octubre del 2019 con el estallido social en Chile y todo este 2020 con la pandemia que nos afecta a nivel mundial. Hoy debemos hacer una nueva pausa. Luego de trabajar constantemente con la esperanza que todo pudiera tomar otro camino, lamentablemente no están las condiciones para volver a reencontrarnos este 2020. Es por ello que la nueva fecha para Creamfields Chile será el 6 y 7 de noviembre del 2021. Sabemos que falta mucho, pero somos realistas y no queremos generar falsas expectativas frente a la incertidumbre del contexto actual que vivimos. Llevamos 15 años construyendo una gran historia junto a todos ustedes #CreamfieldsLovers, con nuestro equipo, auspiciadores y colaboradores que versión a versión avanzamos con nuevas propuestas en experiencia y entretenimiento total. Esto hizo que nuestras últimas ediciones fueran catalogadas como: el festival más importante de música electrónica en Sudamérica. Respecto a tu ticket, este será válido para la próxima edición e incluirá diversos beneficios que podrás conocer más en detalle en www.creamfields.cl o www.puntoticket.com/creamfields. Para aquellos que prefieran la devolución de su dinero, podrán realizarlo desde 21 de septiembre al 16 de octubre 2020. A todos los que eligieron conservar su boleto y permanecer con nosotros durante este nuevo viaje a Creamfields Chile 2021 ¡Muchas Gracias! es una gran ayuda para todos los que trabajamos en organizar el festival. Eres la comunidad más increíble a la que podemos pertenecer. Esto significa mucho para nosotros. "
  },
  getters: {},
  mutations: {},
  actions: {},
};
